=== rajkumaar23/ncp/XML-evaluation/university-database.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema" 
targetNamespace="https://www.w3schools.com"
>
  <xs:element name="university">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" name="semester">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="type" type="xs:string" />
              <xs:element name="year" type="xs:int" />
              <xs:element name="courses">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element maxOccurs="unbounded" name="course">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="name" type="xs:string" />
                          <xs:element name="faculty" type="xs:string" />
                          <xs:element minOccurs="0" name="studentsCount" type="xs:int" />
                          <xs:element name="days">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element maxOccurs="7" name="day" type="xs:string" />
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                          <xs:element name="start" type="xs:time" />
                          <xs:element name="end" type="xs:time" />
                          <xs:element minOccurs="0" name="venue" type="xs:string" />
                          <xs:element minOccurs="0" name="lab">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="days">
                                  <xs:complexType>
                                    <xs:sequence>
                                      <xs:element name="day" type="xs:string" />
                                    </xs:sequence>
                                  </xs:complexType>
                                </xs:element>
                                <xs:element name="start" type="xs:string" />
                                <xs:element name="end" type="xs:string" />
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== rajkumaar23/ncp/XML-evaluation/university.xml
<?xml version="1.0" encoding="UTF-8"?>

<university xmlns="https://www.w3schools.com"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="https://www.w3schools.com university-database.xsd"> 
  <semester> 
    <type>ODD</type>  
    <year>2008</year>  
    <courses> 
      <course> 
        <name>Introduction to Database Management Systems</name>  
        <faculty>Gupta</faculty>  
        <days> 
          <day>Monday</day>  
          <day>Wednesday</day> 
        </days>  
        <start>09:00:00</start>  
        <end>11:00:00</end>  
        <venue>C402</venue>  
        <lab> 
          <days> 
            <day>Friday</day> 
          </days>  
          <start>09:45:00</start>  
          <end>12:20:00</end> 
        </lab> 
      </course>  
      <course> 
        <name>Advanced Database Management Systems</name>  
        <faculty>Menon</faculty>  
        <studentsCount>35</studentsCount>  
        <days> 
          <day>Monday</day>  
          <day>Tuesday</day>  
          <day>Thursday</day> 
        </days>  
        <start>13:10:00</start>  
        <end>14:00:00</end>  
        <venue>C401</venue> 
      </course> 
    </courses> 
  </semester>  
  <semester> 
    <type>ODD</type>  
    <year>2009</year>  
    <courses> 
      <course> 
        <name>Introduction to Database Management Systems</name>  
        <faculty>Dr. Priya</faculty>  
        <studentsCount>63</studentsCount>  
        <days> 
          <day>Tuesday</day>  
          <day>Thursday</day> 
        </days>  
        <start>15:00:00</start>  
        <end>16:30:00</end>  
        <venue>C405</venue>  
        <lab> 
          <days> 
            <day>Thursday</day> 
          </days>  
          <start>14:10:00</start>  
          <end>16:10:00</end> 
        </lab> 
      </course>  
      <course> 
        <name>Advanced Database Management Systems</name>  
        <faculty>Shankar</faculty>  
        <studentsCount>35</studentsCount>  
        <days> 
          <day>Monday</day>  
          <day>Wednesday</day>  
          <day>Friday</day> 
        </days>  
        <start>09:00:00</start>  
        <end>10:00:00</end> 
      </course> 
    </courses> 
  </semester> 
</university>
